# Generated by Django 5.0.1 on 2024-01-31 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baner',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('img', models.ImageField(upload_to='Baner/')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('choise_insitution', models.CharField(choices=[('bachlor', 'Bakalavr'), ('master', 'Master')], default='bachlor', max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('message', models.TextField()),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('img', models.ImageField(upload_to='Result/')),
                ('name', models.CharField(max_length=100)),
                ('insitute_name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('img', models.ImageField(upload_to='Review/')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('order',),
            },
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Social_acaount',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('icon', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('link', models.URLField()),
            ],
            options={
                'ordering': ('order',),
            },
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Static',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('count_student', models.IntegerField(default=1)),
                ('count_university', models.IntegerField(default=1)),
                ('year_experienced', models.IntegerField(default=1)),
                ('count_country', models.IntegerField(default=1)),
            ],
            bases=('app.basemodel',),
        ),
    ]
